title: آموزش ری اکت به زبان فارسی
description:  در این پروژه سعی بر این است که یک مرجع کامل و به روز فارسی،  در مورد ری اکت و ری اکت نیتیو را داشته باشیم . در مورد همکاری در پروژه لطفا فایل راهنما را مطالعه کنید
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
